version: '3'

services:
  web-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - /app/node_modules
      - ./:/app
  test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: "npm run test"